AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation template for s3 bucket
Resources:
  S3Bucket:
    DeletionPolicy: Retain
    Type: 'AWS::S3::Bucket'
    Description: Creating Amazon S3 bucket from CloudFormation
    Properties:
      BucketName: demo-bucket

  WorkItemBucketBackupRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service:
                - s3.amazonaws.com
    BucketBackupPolicy:
      Type: 'AWS::IAM::Policy'
      Properties:
        PolicyDocument:
          Statement:
            - Sid: "Stmt1544958705029"
              Effect: "Deny"
              NotPrincipal:
                "AWS": "arn:aws:iam::<accountid>:root"
              Action:
                - "s3:DeleteObject"
              Resource:
                - !Join
                  - ''
                  - - 'arn:aws:s3:::'
                    - !Ref RecordServiceS3Bucket
        PolicyName: BucketBackupPolicy
        Roles:
          - !Ref WorkItemBucketBackupRole
Outputs:
  S3Bucket:
    Description: Bucket Created using this template.
    Value: !Ref S3Bucket